# Schema for the configuration files of the Smarty module.
smarty.settings:
  type: config_object
  label: 'Smarty settings'
  mapping:
    key:
      type: string
      label: 'Website Key'
    address_apply_all:
      type: boolean
      label: 'Apply to all address fields'
    disable_complete:
      type: boolean
      label: 'Disable address fields once address is chosen'
